### ISSUE TITLE
Migration to Buster : weird behaviour for some mail accounts

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost-Apps/sogo_ynh#8]
After migrating to Buster, my ynh mail account and one of the IMAP accounts I had added to SoGO are not usable anymore: I see the accounts, they are properly configured in terms of server URLs, but there are no folders nor mails.
Weirdly, the last IMAP account is working fine.
Where could I find some logs to understand what's happening?

**Comment by Josue-T** [comment]
Hello,

A fix is available on the testing branch: https://github.com/YunoHost-Apps/sogo_ynh/tree/testing

**Comment by roukydesbois** [comment]
Is there a way to change the branch of a repo for an installed app? If I uninstall SoGO, and reinstall it, I'll loose the previous buggy installation and won't be sure the fix fixes it, right?

-----
Thomas Blarre

7 août 2020 21:00:39 Josue-T <notifications@github.com>:

**Comment by Josue-T** [comment]
You can see here how to use the testing branch: https://github.com/YunoHost-Apps/sogo_ynh#developers-infos

**Comment by roukydesbois** [comment]
After debugging a bit, my issue is related to https://sogo.nu/bugs/view.php?id=4783
Which is fixed in version 5.0. Is there any plan to upgrade the version of the ynh package pleeeeease? :grimacing: 
Thanks!

**Comment by Josue-T** [comment]
Well, the fix is available since 2 month on master... can you please update your package on the last version ?

**Comment by roukydesbois** [comment]
I've just upgraded it again, just to be sure, and I still don't see my Gandi account's folders, and I have this error when I try to create a folder:

```
Oct 02 19:47:43 sogod [18689]: <0x1646520[SOGoMailAccount]:2> renewing imap4 password                       2020-10-02 19:47:43.194 sogod[18689:18689] ERROR(-[NSException(NGMiscellaneous) initWithFormat:]): missing format!                                                                                                      Oct 02 19:47:43 sogod [18689]: <0x0x1418320[NGImap4Client]> ERROR(-[NGImap4Client _processUnknownCommandParserException:]): catched non-IMAP4 parsing exception UnexpectedEndOfStream: the parsed stream ended unexpectedly                                                                                                         Oct 02 19:47:43 sogod [18689]: [ERROR] <0x0x1387248[NGImap4ConnectionManager]> IMAP4 login failed:            host=mail.gandi.net, user=thomas@blarre.net, pwd=yes                                                        url=imaps://thomas%40blarre.net@mail.gandi.net/                                                             base=(null)                                                                                                 base-class=(null))                                                                                          = <0x0x1418320[NGImap4Client]: login=thomas@blarre.net(pwd) socket=<NGActiveSSLSocket[0x0x19d5160]: mode=rw address=<0x0x165e778[NGInternetSocketAddress]: host=ynh.blarre.net port=38446> connectedTo=<0x0x1676b30[NGInternetSocketAddress]: host=mail.gandi.net port=993>>>                                                     Oct 02 19:47:43 sogod [18689]: [ERROR] <0x1646520[SOGoMailAccount]:2> Could not connect IMAP4               Oct 02 19:47:43 sogod [18689]: 127.0.0.1 "POST /SOGo/so/thomas/Mail/2/createFolder HTTP/1.0" 500 66/15 0.226
```

-----
Thomas Blarre

2 oct. 2020 17:59:05 Josue-T <notifications@github.com>:

**Comment by Josue-T** [comment]
Ah well, I understand your issue. My fix was for the local account not for the remote account...

Well, I know that it's really a big issue but as I use the official debian package I don't think that this fix will be available until debian Bullseye. And I can't use the SOGo repository because not all architecture are supported. But you still can upgrade manually. It's documented here: https://sogo.nu/support/faq/how-to-install-sogo-on-debian.html

**Comment by roukydesbois** [comment]
Thanks for the explanation!

**Comment by Josue-T** [comment]
Closing as we are on debian bullseye and so the issue should be fixed by this way
